# Generated by Django 4.1.4 on 2023-02-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
